<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>php</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(/\*|\{|\()</string>
	<key>foldingStopMarker</key>
	<string>(\*/|\}|\))</string>
	<key>name</key>
	<string>Lithium</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\?&gt;</string>
			<key>name</key>
			<string>class.controller.lithium</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$this-&gt;</string>
			<key>name</key>
			<string>keyword.this.class.lithium</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.method.class.lithium</string>
				</dict>
			</dict>
			<key>match</key>
			<string>($this-&gt;)([a-zA-Z]+)(\()\b</string>
			<key>name</key>
			<string>support.method.class.lithium</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.method.class.lithium</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(static::)([a-zA-Z]+)(\()\b</string>
			<key>name</key>
			<string>support.method.static.lithium</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.method.class.lithium</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\$this-&gt;[a-zA-Z]*</string>
			<key>name</key>
			<string>support.member.class.lithium</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.method.class.lithium</string>
				</dict>
			</dict>
			<key>match</key>
			<string>static::\$[a-zA-Z]*</string>
			<key>name</key>
			<string>support.member.static.lithium</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(config|find|finder|meta|key|relations|bind|schema|hasField|create|save|validates|delete|update|remove|_name|_connection|applyFilter|_filter|_object|_relations|_isBase|_findFilters)\b</string>
			<key>name</key>
			<string>support.function.model.lithium</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(hasOne|belongsTo|hasMany|_meta|_schema)\b</string>
			<key>name</key>
			<string>support.property.model.lithium</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(redirect|set|__invoke|render)\b</string>
			<key>name</key>
			<string>support.function.controller.lithium</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(response|request|_render|_data)\b</string>
			<key>name</key>
			<string>support.property.controller.lithium</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(link|script|style|submit|password|textarea|checkbox|style|file|hidden|image|field|radio|error)\b</string>
			<key>name</key>
			<string>support.function.helper.html.lithium</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(write|read|delete|check|config)\b</string>
			<key>name</key>
			<string>support.function.storage.lithium</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.php</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.php.lithium</string>
	<key>uuid</key>
	<string>5B4B0819-4357-4AD0-84CA-B5A7DC23B1B1</string>
</dict>
</plist>
